# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "E:/code/HDL/hardware_design/func_inst/project_1/.Xil/Vivado-5980-LapTop-TanYong/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7a100tcsg324-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    E:/code/HDL/hardware_design/func_inst/rtl/myCPU/utils
    E:/code/HDL/hardware_design/func_inst/rtl/xilinx_ip/data_ram
    E:/code/HDL/hardware_design/func_inst/rtl/xilinx_ip/inst_ram
  } D:/develop/vivado2021/Vivado/2021.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
      rt::read_verilog -include {
    E:/code/HDL/hardware_design/func_inst/rtl/myCPU/utils
    E:/code/HDL/hardware_design/func_inst/rtl/xilinx_ip/data_ram
    E:/code/HDL/hardware_design/func_inst/rtl/xilinx_ip/inst_ram
  } {
      E:/code/HDL/hardware_design/func_inst/project_1/.Xil/Vivado-5980-LapTop-TanYong/realtime/data_ram_stub.v
      E:/code/HDL/hardware_design/func_inst/project_1/.Xil/Vivado-5980-LapTop-TanYong/realtime/inst_ram_stub.v
      E:/code/HDL/hardware_design/func_inst/rtl/myCPU/adder.v
      E:/code/HDL/hardware_design/func_inst/rtl/myCPU/alu.v
      E:/code/HDL/hardware_design/func_inst/rtl/myCPU/aludec.v
      E:/code/HDL/hardware_design/func_inst/rtl/myCPU/controller.v
      E:/code/HDL/hardware_design/func_inst/rtl/myCPU/datapath.v
      E:/code/HDL/hardware_design/func_inst/rtl/myCPU/div.v
      E:/code/HDL/hardware_design/func_inst/rtl/myCPU/eqcmp.v
      E:/code/HDL/hardware_design/func_inst/rtl/myCPU/flopenr.v
      E:/code/HDL/hardware_design/func_inst/rtl/myCPU/flopenrc.v
      E:/code/HDL/hardware_design/func_inst/rtl/myCPU/flopr.v
      E:/code/HDL/hardware_design/func_inst/rtl/myCPU/floprc.v
      E:/code/HDL/hardware_design/func_inst/rtl/myCPU/hazard.v
      E:/code/HDL/hardware_design/func_inst/rtl/myCPU/hilo_reg.v
      E:/code/HDL/hardware_design/func_inst/rtl/myCPU/utils/instdec.v
      E:/code/HDL/hardware_design/func_inst/rtl/myCPU/maindec.v
      E:/code/HDL/hardware_design/func_inst/rtl/myCPU/mips.v
      E:/code/HDL/hardware_design/func_inst/rtl/myCPU/mux2.v
      E:/code/HDL/hardware_design/func_inst/rtl/myCPU/mux3.v
      E:/code/HDL/hardware_design/func_inst/rtl/myCPU/mux4.v
      E:/code/HDL/hardware_design/func_inst/rtl/myCPU/mycpu_top.v
      E:/code/HDL/hardware_design/func_inst/rtl/myCPU/pc.v
      E:/code/HDL/hardware_design/func_inst/rtl/myCPU/regfile.v
      E:/code/HDL/hardware_design/func_inst/rtl/myCPU/signext.v
      E:/code/HDL/hardware_design/func_inst/rtl/myCPU/sl2.v
      E:/code/HDL/hardware_design/func_inst/rtl/top.v
    }
      rt::read_vhdl -lib xpm D:/develop/vivado2021/Vivado/2021.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top top
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "E:/code/HDL/hardware_design/func_inst/project_1/.Xil/Vivado-5980-LapTop-TanYong/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
